name: workflow overview

on:
  workflow_dispatch:
  push:
    branches:
    - main
jobs:
  my_self-hosted_jobs:
    name: my self hosted job
    runs-on: self-hosted
    steps:
      - name: step in a self-hosted runner
        id: selfHostedId
        shell: cmd
        run:
          echo This is a multiline comment
          echo and This job has been executed from my self-hosted runner
    
  a_simple_job:
    name: my simple job name
    runs-on: ubuntu-latest
    steps:
      - name: name of my step
        id: stepId
        run: echo "This is the first step from the first job"
      - name: step with another shell
        id: ShellStep
        shell: python
        run: print("This step is using Python shell")
        
        
     
    
  

